# Generated by Django 4.2.27 on 2026-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sm_key', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Size Key')),
                ('sm_description', models.CharField(max_length=50, verbose_name='Size Description')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'db_table': 'size',
                'ordering': ['sm_key'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='loadinginformation',
            options={'managed': False, 'ordering': ['-dated'], 'verbose_name': 'Loading Information', 'verbose_name_plural': 'Loading Information'},
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='line_no',
            field=models.CharField(choices=[('line-21', 'Line-21'), ('line-22', 'Line-22'), ('line-23', 'Line-23'), ('line-24', 'Line-24'), ('line-25', 'Line-25'), ('line-26', 'Line-26'), ('line-27', 'Line-27'), ('line-28', 'Line-28'), ('line-29', 'Line-29'), ('line-30', 'Line-30'), ('line-31', 'Line-31'), ('line-32', 'Line-32'), ('line-all', 'Line-all'), ('line-6r', 'Line-6r'), ('line-7a', 'Line-7a')], max_length=10, verbose_name='Line Number'),
        ),
    ]
