# Generated by Django 4.2.27 on 2026-01-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0002_size_alter_loadinginformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('cm_key', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Color Key')),
                ('cm_short_description', models.CharField(max_length=50, verbose_name='Color Short Description')),
                ('cm_description', models.CharField(max_length=100, verbose_name='Color Description')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'color',
                'ordering': ['cm_key'],
                'managed': True,
            },
        ),
    ]
