# Generated by Django 4.2.27 on 2026-01-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Style Key')),
                ('style_description', models.CharField(max_length=100, verbose_name='Style Description')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'db_table': 'style',
                'ordering': ['style_key'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LineTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_date', models.DateField(verbose_name='Production Date')),
                ('line_no', models.CharField(choices=[('line-21', 'Line-21'), ('line-22', 'Line-22'), ('line-23', 'Line-23'), ('line-24', 'Line-24'), ('line-25', 'Line-25'), ('line-26', 'Line-26'), ('line-27', 'Line-27'), ('line-28', 'Line-28'), ('line-29', 'Line-29'), ('line-30', 'Line-30'), ('line-31', 'Line-31'), ('line-32', 'Line-32')], max_length=10, verbose_name='Line Number')),
                ('target_qty', models.IntegerField(default=0, verbose_name='Target Quantity')),
                ('produced_qty', models.IntegerField(default=0, verbose_name='Produced Quantity')),
                ('wip_qty', models.IntegerField(default=0, verbose_name='wip Quantity')),
                ('total_smv', models.FloatField(default=0.0, verbose_name='Total SMV')),
                ('efficiency', models.FloatField(default=0.0, verbose_name='Efficiency (%)')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('articleno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.operationinformation', verbose_name='Article')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.operationinformation', verbose_name='Color')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.loadinginformation', verbose_name='Item Name')),
                ('pono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.loadinginformation', verbose_name='PO #')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.operationinformation', verbose_name='Zize')),
            ],
            options={
                'verbose_name': 'Line Target',
                'verbose_name_plural': 'LineTarget',
                'db_table': 'line_tareget',
                'ordering': ['-p_date'],
                'managed': True,
            },
        ),
    ]
