# Generated by Django 4.2.27 on 2026-01-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0004_style_linetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylePlannedOrder',
            fields=[
                ('stpo_key', models.AutoField(primary_key=True, serialize=False, verbose_name='STPO Key')),
                ('stpo_id', models.CharField(max_length=50, verbose_name='STPO ID')),
                ('stpo_ci_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('stpo_qty', models.IntegerField(verbose_name='Planned Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(verbose_name='Modified Date')),
                ('stpo_plan_start_date', models.DateField(blank=True, null=True, verbose_name='Plan Start Date')),
                ('stpo_plan_finish_date', models.DateField(blank=True, null=True, verbose_name='Plan Finish Date')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('cm_key', models.ForeignKey(db_column='cm_key', on_delete=django.db.models.deletion.CASCADE, to='hangerline.color', verbose_name='Color')),
                ('sm_key', models.ForeignKey(db_column='sm_key', on_delete=django.db.models.deletion.CASCADE, to='hangerline.size', verbose_name='Size')),
                ('st_id', models.ForeignKey(db_column='st_id', on_delete=django.db.models.deletion.CASCADE, to='hangerline.style', verbose_name='Style')),
            ],
            options={
                'verbose_name': 'Style Planned Order',
                'verbose_name_plural': 'Style Planned Orders',
                'db_table': 'style_planned_order',
                'ordering': ['-created_date'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='LineTarget',
        ),
    ]
