# Generated by Django 4.2.27 on 2026-01-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0005_styleplannedorder_delete_linetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_connection', models.CharField(choices=[('line-21', 'Line-21'), ('line-22', 'Line-22'), ('line-23', 'Line-23'), ('line-24', 'Line-24'), ('line-25', 'Line-25'), ('line-26', 'Line-26'), ('line-27', 'Line-27'), ('line-28', 'Line-28'), ('line-29', 'Line-29'), ('line-30', 'Line-30'), ('line-31', 'Line-31'), ('line-32', 'Line-32')], max_length=10, verbose_name='Line')),
                ('target_date', models.DateField(verbose_name='Target Date')),
                ('total_target_qty', models.IntegerField(default=0, verbose_name='Total Target Quantity')),
            ],
            options={
                'verbose_name': 'Line Target',
                'verbose_name_plural': 'Line Targets',
                'db_table': 'line_target',
                'ordering': ['-target_date', 'source_connection'],
                'managed': True,
                'unique_together': {('source_connection', 'target_date')},
            },
        ),
        migrations.AlterField(
            model_name='styleplannedorder',
            name='cm_key',
            field=models.ForeignKey(blank=True, db_column='cm_key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangerline.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='styleplannedorder',
            name='sm_key',
            field=models.ForeignKey(blank=True, db_column='sm_key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangerline.size', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='styleplannedorder',
            name='st_id',
            field=models.ForeignKey(blank=True, db_column='st_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangerline.style', verbose_name='Style'),
        ),
        migrations.CreateModel(
            name='LineTargetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, verbose_name='Item ID')),
                ('item_title', models.CharField(max_length=100, verbose_name='Item Title')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('barcode', models.BigIntegerField(verbose_name='Barcode')),
                ('scrvoucher_no', models.TextField(blank=True, null=True, verbose_name='SCR Voucher No')),
                ('bundleno', models.BigIntegerField(verbose_name='Bundle No')),
                ('target_qty', models.IntegerField(verbose_name='Target Quantity')),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=10, verbose_name='Shift')),
                ('cm_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.color', verbose_name='Color')),
                ('linetarget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.linetarget', verbose_name='Line Target')),
                ('sm_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.size', verbose_name='Size')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.style', verbose_name='Style')),
                ('stpo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangerline.styleplannedorder', verbose_name='Style Planned Order')),
            ],
            options={
                'verbose_name': 'Line Target Detail',
                'verbose_name_plural': 'Line Target Details',
                'db_table': 'line_target_detail',
                'ordering': ['linetarget', 'shift', 'stpo_id'],
                'managed': True,
            },
        ),
    ]
