# Generated by Django 4.2.27 on 2026-01-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0006_linetarget_alter_styleplannedorder_cm_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetargetdetail',
            name='cm_key',
            field=models.CharField(max_length=10, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='linetarget',
            field=models.ForeignKey(db_column='linetarget_id', on_delete=django.db.models.deletion.CASCADE, to='hangerline.linetarget', verbose_name='Line Target'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='sm_key',
            field=models.CharField(max_length=10, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='st_id',
            field=models.ForeignKey(db_column='st_id', on_delete=django.db.models.deletion.CASCADE, to='hangerline.style', verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='stpo_id',
            field=models.ForeignKey(db_column='stpo_id', on_delete=django.db.models.deletion.CASCADE, to='hangerline.styleplannedorder', verbose_name='Style Planned Order'),
        ),
    ]
