# Generated by Django 4.2.27 on 2026-01-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0007_alter_linetargetdetail_cm_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linetargetdetail',
            options={'managed': True, 'ordering': ['linetarget', 'shift', 'pono'], 'verbose_name': 'Line Target Detail', 'verbose_name_plural': 'Line Target Details'},
        ),
        migrations.RemoveField(
            model_name='linetargetdetail',
            name='stpo_id',
        ),
        migrations.AddField(
            model_name='linetarget',
            name='loading_qty',
            field=models.IntegerField(default=0, verbose_name='Loading Quantity'),
        ),
        migrations.AddField(
            model_name='linetarget',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='linetargetdetail',
            name='pono',
            field=models.CharField(default='', max_length=10, verbose_name='PO No'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='item_id',
            field=models.CharField(max_length=20, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='item_title',
            field=models.CharField(max_length=200, verbose_name='Item Title'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='scrvoucher_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SCR Voucher No'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='st_id',
            field=models.CharField(max_length=10, verbose_name='Style'),
        ),
    ]
