# Generated by Django 4.2.27 on 2026-01-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0008_alter_linetargetdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linetarget',
            name='loading_qty',
            field=models.IntegerField(default=0, verbose_name='Loading Quantity'),
        ),
    ]
