# Generated by Django 4.2.27 on 2026-01-02 05:21

from django.db import migrations, models
import hangerline.models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0009_add_missing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linetargetdetail',
            name='st_id',
        ),
        migrations.AlterField(
            model_name='linetarget',
            name='loading_qty',
            field=models.IntegerField(default=0, verbose_name='DTS Quantity'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='pono',
            field=models.CharField(default='', max_length=10, verbose_name='PO No'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='target_qty',
            field=models.IntegerField(verbose_name='DTS Qty'),
        ),
    ]
