# Generated by Django 4.2.27 on 2026-01-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0010_remove_linetargetdetail_st_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linetargetdetail',
            name='st_id',
            field=models.CharField(choices=[], default='', max_length=50, verbose_name='Style ID'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='pono',
            field=models.CharField(choices=[], default='', max_length=10, verbose_name='PO No'),
        ),
    ]
