# Generated by Django 4.2.27 on 2026-01-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0011_linetargetdetail_st_id_alter_linetargetdetail_pono'),
    ]

    operations = [
        migrations.AddField(
            model_name='linetargetdetail',
            name='stpo_key_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangerline.styleplannedorder', verbose_name='Style Planned Order'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='pono',
            field=models.CharField(choices=[('dummy', 'dummy')], default='', max_length=10, verbose_name='PO No'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='st_id',
            field=models.CharField(choices=[('dummy', 'dummy')], default='', max_length=50, verbose_name='Style ID'),
        ),
    ]
