# Generated by Django 4.2.27 on 2026-01-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0012_linetargetdetail_stpo_key_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetargetdetail',
            name='barcode',
            field=models.BigIntegerField(null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='bundleno',
            field=models.BigIntegerField(null=True, verbose_name='Bundle No'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='cm_key',
            field=models.ForeignKey(blank=True, db_column='cm_key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangerline.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='item_id',
            field=models.CharField(max_length=20, null=True, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='item_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Item Title'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='pono',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='PO No'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=10, null=True, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='sm_key',
            field=models.ForeignKey(blank=True, db_column='sm_key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangerline.size', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='st_id',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Style ID'),
        ),
    ]
