# Generated by Django 4.2.27 on 2026-01-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0013_alter_linetargetdetail_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linetargetdetail',
            name='stpo_key_id',
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='pono',
            field=models.CharField(max_length=10, null=True, verbose_name='PO No'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='st_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Style ID'),
        ),
        migrations.DeleteModel(
            name='StylePlannedOrder',
        ),
    ]
