# Generated by Django 4.2.27 on 2026-01-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0014_remove_linetargetdetail_stpo_key_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pono', models.CharField(blank=True, null=True)),
                ('client_id', models.BigIntegerField(blank=True, null=True)),
                ('client_title', models.CharField(blank=True, null=True)),
                ('buyyear', models.IntegerField(blank=True, null=True)),
                ('buymonth', models.IntegerField(blank=True, null=True)),
                ('clientpodate', models.DateTimeField(blank=True, null=True)),
                ('vtp', models.CharField(blank=True, null=True)),
                ('vyear', models.IntegerField(blank=True, null=True)),
                ('mnth', models.IntegerField(blank=True, null=True)),
                ('vno', models.IntegerField(blank=True, null=True)),
                ('scrvoucher_no', models.CharField(blank=True, null=True)),
                ('srno', models.BigIntegerField(blank=True, null=True)),
                ('divisionbygroup', models.CharField(blank=True, null=True)),
                ('item_id', models.CharField(blank=True, null=True)),
                ('articleno', models.CharField(blank=True, null=True)),
                ('mcombo', models.CharField(blank=True, null=True)),
                ('mcolour', models.CharField(blank=True, null=True)),
                ('itemsize', models.CharField(blank=True, null=True)),
                ('item_title', models.CharField(blank=True, null=True)),
                ('po_qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Purchase Order',
                'verbose_name_plural': 'ClientPurchaseOrders',
                'db_table': 'clientpurchaseorder',
                'ordering': ['-clientpodate'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='linetargetdetail',
            options={'managed': True, 'ordering': ['linetarget', 'pono', 'articleno', 'color__cm_key', 'size__sm_key'], 'verbose_name': 'Line Target Detail', 'verbose_name_plural': 'Line Target Details'},
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='st_id',
            field=models.CharField(db_column='st_id', max_length=50, null=True, verbose_name='Style ID'),
        ),
        migrations.RenameField(
            model_name='linetargetdetail',
            old_name='st_id',
            new_name='articleno',
        ),
        migrations.RenameField(
            model_name='linetargetdetail',
            old_name='cm_key',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='linetargetdetail',
            old_name='sm_key',
            new_name='size',
        ),
        migrations.AddField(
            model_name='linetargetdetail',
            name='cpo_id',
            field=models.ForeignKey(blank=True, db_column='cpo_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hangerline.clientpurchaseorder', verbose_name='Client Purchase Order'),
        ),
    ]
