# Generated by Django 4.2.27 on 2026-01-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0015_clientpurchaseorder_alter_linetargetdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetargetdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
