# Generated by Django 4.2.27 on 2026-01-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0016_fix_linetargetdetail_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create sequence if it doesn't exist
            CREATE SEQUENCE IF NOT EXISTS line_target_detail_id_seq;

            -- Set the sequence owned by the id column
            ALTER SEQUENCE line_target_detail_id_seq OWNED BY line_target_detail.id;

            -- Set the column default to use the sequence
            ALTER TABLE line_target_detail ALTER COLUMN id SET DEFAULT nextval('line_target_detail_id_seq');

            -- Set the current value of the sequence to the maximum id + 1
            SELECT setval('line_target_detail_id_seq', COALESCE((SELECT MAX(id) FROM line_target_detail), 0) + 1, false);
            """,
            reverse_sql="""
            -- Reverse operations
            ALTER TABLE line_target_detail ALTER COLUMN id DROP DEFAULT;
            ALTER SEQUENCE line_target_detail_id_seq OWNED BY NONE;
            """
        ),
    ]
