# Generated by Django 4.2.27 on 2026-01-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0017_fix_linetargetdetail_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferToPacking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dated', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('proddate', models.DateField(blank=True, null=True, verbose_name='Production Date')),
                ('scrvoucher_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='SCR Voucher No')),
                ('transferfromdepartment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Transfer From Department ID')),
                ('from_dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='From Department Name')),
                ('transfertodepartment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Transfer To Department ID')),
                ('to_dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='To Department Name')),
                ('pono', models.CharField(blank=True, max_length=50, null=True, verbose_name='PO No')),
                ('articleno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Article No')),
                ('mcolour', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size')),
                ('item_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item ID')),
                ('item_title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Item Title')),
                ('qtytransferred', models.IntegerField(blank=True, null=True, verbose_name='Quantity Transferred')),
                ('refqty', models.IntegerField(blank=True, null=True, verbose_name='Reference Quantity')),
                ('line_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Line ID')),
                ('line_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line Description')),
                ('bundleno', models.BigIntegerField(blank=True, null=True, verbose_name='Bundle No')),
            ],
            options={
                'verbose_name': 'Transfer to Packing',
                'verbose_name_plural': 'Transfer to Packing',
                'db_table': 'transfertopacking',
                'ordering': ['-dated'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='linetarget',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='linetargetdetail',
            name='target_qty',
            field=models.IntegerField(null=True, verbose_name='Target Qty'),
        ),
    ]
