# Generated by Django 4.2.27 on 2026-01-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0018_transfertopacking_alter_linetarget_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linetarget',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterUniqueTogether(
            name='linetarget',
            unique_together={('source_connection', 'target_date', 'shift')},
        ),
    ]
