# Generated by Django 4.2.27 on 2026-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0019_auto_20260120_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Line Code')),
                ('type', models.CharField(choices=[('6r', '6R'), ('7a', '7A')], max_length=2, verbose_name='Line Type')),
                ('name', models.CharField(max_length=50, verbose_name='Line Name')),
                ('server_id', models.CharField(max_length=50, verbose_name='Server ID')),
                ('server_name', models.CharField(max_length=100, verbose_name='Server Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
                'db_table': 'line',
                'ordering': ['code'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='linetarget',
            options={'managed': True, 'ordering': ['-target_date', 'source_connection', 'shift'], 'verbose_name': 'Line Target', 'verbose_name_plural': 'Line Targets'},
        ),
        migrations.AlterField(
            model_name='linetarget',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=10, verbose_name='Shift'),
        ),
    ]
