# Generated by Django 4.2.27 on 2026-01-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangerline', '0020_line_alter_linetarget_options_alter_linetarget_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='server_id',
            new_name='server_ip',
        ),
    ]
